# Generated by Django 4.2.14 on 2024-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='prices',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
